version: '3.3'

services:
  # Serviço PHP-FPM
  app:
    build:
      context: . # Procura o Dockerfile no diretório atual
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped # Reinicia o contêiner se ele parar
    ports:
      - "8000:8000" # Mapeia a porta 80 do host para a porta 80 do contêiner
    volumes:
      - ../:/var/www/html # Monta o diretório do seu projeto Laravel dentro do contêiner
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Serviço Nginx
  nginx:
    image: nginx:stable-alpine # Imagem leve do Nginx
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8200:80" # Mapeia a porta 80 do host para a porta 80 do contêiner
    volumes:
      - ../:/var/www/html # Monta o diretório do projeto Laravel
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Arquivo de configuração do Nginx
    depends_on:
      - app # Nginx depende do serviço PHP-FPM
#      - thalamusdb # Opcional: Nginx pode depender do DB para certas verificações

  trustme-db:
    image: mysql:8-debian
    container_name: trustme-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
